# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  unit-test:
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12']
        platform: [ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: poetry install
    - name: Test with unittest
      run: |
        poetry run python -m unittest discover test
